Added DL cases for typescript cdk
aws-samples/amazon-q-detectors pull request #34
Opened 2024-11-13 13:00 UTC by shreyabhagat1

Add non compliant and compliant samples for typescript_cdk detectors.

Note: All the test cases have 100% recall and precision.

2024-11-13 13:32 UTC, bhaaayus requested changes

2024-11-13 13:32 UTC, bhaaayus commented on cdk_typescript/src/detectors/typescript_cdk_allows_rds_db_security_group_for_inbound_access/typescript_cdk_allows_rds_db_security_group_for_inbound_access_compliant.ts
> +    constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
Some files have 4 space indents while some have 2 space indents.

2024-11-14 07:57 UTC, bhaaayus approved these changes

2024-11-18 08:29 UTC, atonaamz approved these changes

2024-11-18 08:29 UTC, merged