Add non compliant and compliant samples for Go detectors
aws-samples/amazon-q-detectors pull request #4
Opened 2024-11-04 15:23 UTC by ankit-amazon

#### Add non compliant and compliant samples for Go detectors. 
Note: All the test cases have 100% recall and precision.

2024-11-04 16:36 UTC, bhaaayus requested changes
Please address the comments

2024-11-04 16:36 UTC, bhaaayus commented on src/rule_based_detector_library/GO/detectors/go-hidden-goroutine/go-hidden-goroutine_compliant.go
> +		if 5%2 == 0 {
`%` should have one space before and after for better readability

2024-11-04 16:36 UTC, bhaaayus commented on src/rule_based_detector_library/GO/detectors/go-hidden-goroutine/go-hidden-goroutine_compliant.go
> +	if 8%2 == 0 {
`%` should have one space before and after for better readability. Please incorporate these changes for all the files.

2024-11-04 16:36 UTC, bhaaayus commented on src/rule_based_detector_library/GO/detectors/go-http-listenandservetls/go-http-listenandservetls_compliant.go
> +func httpListenandservetlsCompliant(certFile string, keyFile string) {
Should be `httpListenAndServeTLSCompliant`

2024-11-04 16:36 UTC, bhaaayus commented on src/rule_based_detector_library/GO/detectors/go-http-listenandservetls/go-http-listenandservetls_non-compliant.go
> +func httpListenandservetlsNoncompliant() {
Should be `httpListenAndServeTLSNoncompliant`

2024-11-05 07:56 UTC, bhaaayus approved these changes

2024-11-05 18:11 UTC, atonaamz approved these changes

2024-11-05 18:16 UTC, atonaamz submitted a review, later dismissed

2024-11-05 18:53 UTC, atonaamz commented
Can we have the same move these samples to `go/src/detectors`?

2024-11-06 17:40 UTC, atonaamz approved these changes

2024-11-07 18:47 UTC, merged