Added Python DL Cases
aws-samples/amazon-q-detectors pull request #56
Opened 2024-12-03 06:48 UTC by braraiha

- Added detector library cases for python.

- **Note:** All the test cases have 100% recall and precision.

2024-12-03 11:19 UTC, bhaaayus requested changes

2024-12-03 11:19 UTC, bhaaayus commented on python/src/detectors/python-xxe-vulnerability/python-xxe-vulnerability_compliant.py
> +    # Noncompliant: Using `defusedxml.etree.parse` prevents to an XXE injection.
Sentence formation - ~to an~

2024-12-03 11:19 UTC, bhaaayus commented on python/src/detectors/python-zip-slip/python-zip-slip_non-compliant.py
> +    zf = zipfile.ZipFile(archive_name)
Is this applicable for all ZIP files or just the zip files coming from HTTP?
If it's for all zip files, we don't need the Flask stuff
If it's for HTTP -> It should have a decorator with proper route and `archive_name` should come from an HTTP request object

2024-12-04 10:23 UTC, bhaaayus requested changes

2024-12-04 10:23 UTC, bhaaayus commented on python/src/detectors/python-insecure-deserilization/python-insecure-deserilization_non-compliant.py
> +    # Noncompliant: Untrusted user inputs is in the `yaml.load_all`.
Since there's only one input, it would be `input`~s~

2024-12-04 11:13 UTC, bhaaayus approved these changes

2024-12-05 20:39 UTC, grl-wang approved these changes

2024-12-06 00:10 UTC, merged